### ISSUE TITLE
インデントを自動で揃えるための拡張機能を追加する

### ISSUE THREAD

**Issue by couragenki** [kanyamalP/kanap-site#1]
## 問題
インデントが崩れてしまうとコーディングの際にコードが読みにくくなり
特にHTMLでは閉じタグの場所がわかりにくくなりミスの原因になります。
https://github.com/kanyamalP/kanap-site/blob/master/index.html#L71

## 対策
エディタの設定を変更することで自動で整形することが可能です。
また不要なスペースの削除などの設定も可能です。
https://qiita.com/mitashun/items/e2f118a9ca7b96b97840

**Comment by kanyamalP** [comment]
修正しました！
https://github.com/kanyamalP/kanap-site/commit/78ba7c1fd75029ab39b4a4bf5fabc019a7146d72

**Comment by couragenki** [comment]
LGTMです。
自動化できるものはどんどん自動化して行くことでミスを無くし
効率的に作業を進めることができるようになるので意識してみてください。

![images](https://user-images.githubusercontent.com/32010156/89706252-d03de980-d99e-11ea-95c6-ba8d68f3ae02.jpeg)

**Comment by couragenki** [comment]
@kanyamalP 
issueをクローズしましょう
